version: '0.1.{build}'

environment:
  AHK_PATH: C:\ahk\AutoHotkey.exe
  AHK_DEBUG: true

install:
  - appveyor DownloadFile https://github.com/Lexikos/AutoHotkey_L/releases/download/v1.1.30.01/AutoHotkey_1.1.30.01_setup.exe -FileName ahk_install.exe
  - ahk_install.exe /S /D=C:\ahk
  - cmd: .\ci\install.bat

build_script:
  - cmd: .\ci\build.bat

artifacts:
  - name: dist
    path: dist\*

test_script:
  - cmd: .\ci\runtests.bat
  - ps: |
       $wc = New-Object 'System.Net.WebClient';
       Get-ChildItem .\reports |
       Foreach-Object {
           $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_.FullName))
       }


on_success:
  - coveralls

cache:
  - venv -> ci\ci_requirements.txt
  - deploy_venv

deploy_script:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG) {
        py -3.7 -m venv deploy_venv
        .\deploy_venv\Scripts\activate.ps1
        python -m pip install --upgrade pip
        pip install --upgrade wheel
        pip install --upgrade twine
        twine upload dist\*
      } else {
        echo "Skipping Deploy Because this is not a tagged commit"
      }
