version: '0.1.{build}'

environment:
  AHK_PATH: C:\ahk\AutoHotkey.exe
  AHK_DEBUG: true

install:
  - ps: |
      if (!(Test-Path ahk_install.exe)) {
          echo "Downloading AHK installer"
          appveyor DownloadFile https://github.com/Lexikos/AutoHotkey_L/releases/download/v1.1.30.01/AutoHotkey_1.1.30.01_setup.exe -FileName ahk_install.exe
      } else {
          echo "Using cached installer"
      }
  - ahk_install.exe /S /D=C:\ahk
  - cmd: .\ci\install.bat

build_script:
  - cmd: .\ci\build.bat

artifacts:
  - name: dist
    path: dist\*

test_script:
  - powershell .\ci\runtests.ps1

on_finish:
  - ps: |
      venv\Scripts\activate.ps1
      if (Test-Path env:COVERALLS_REPO_TOKEN ) { 
          python -m coveralls
      } else {
          python -m coverage
      }
      

cache:
  - ahk_install.exe -> appveyor.yml

deploy_script:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        py -3.7 -m venv deploy_venv
        .\deploy_venv\Scripts\activate.ps1
        python -m pip install --upgrade pip
        pip install --upgrade wheel
        pip install --upgrade twine
        twine upload dist\*
      } else {
        echo "Skipping Deploy Because this is not a tagged commit"
      }
